"use client";

import { useState } from "react";
import { IconBrandGithub } from "@tabler/icons-react";
import { CloudShader } from "@/components/ui/cloud-shader";
import { Carousel, type SkillCard } from "@/components/ui/apple-cards-carousel";
import { PixelatedCanvas } from "@/components/ui/pixelated-canvas";
import { CanvasRevealEffect } from "@/components/ui/canvas-reveal-effect";
import { LampContainer } from "@/components/ui/lamp";
import { WobbleCard } from "@/components/ui/wobble-card";
import { BackgroundLines } from "@/components/ui/background-lines";
import { ProjectShowcase } from "@/components/project-showcase";
import { caseStudy } from "@/lib/portfolio-data";

const skillGroups: SkillCard[] = [
  { label: "01 / Languages", title: "The primitives", description: "Typed foundations for reliable product work.", skills: ["TypeScript", "JavaScript", "Python", "Java", "SQL"], tone: "tone-sky" },
  { label: "02 / Frontend", title: "Interfaces that hold up", description: "React systems built for speed, clarity, and scale.", skills: ["React", "Next.js (App Router, RSC)", "Module Federation", "Redux Toolkit", "Core Web Vitals", "Jest", "React Testing Library", "Cypress"], tone: "tone-lilac" },
  { label: "03 / Backend", title: "The engine room", description: "Typed APIs and durable services behind the interface.", skills: ["Node.js", "Express", "GraphQL", "Spring Boot", "PostgreSQL", "Liquibase", "Redis", "WebSockets", "REST API design"], tone: "tone-ink" },
  { label: "04 / Agentic AI", title: "Tools that think", description: "Grounded agents that can operate real systems.", skills: ["LangGraph", "MCP server development", "Tool-calling agents", "RAG (pgvector)", "Cross-encoder reranking", "LLM evaluation", "Hit-rate@k", "MRR", "LLM-as-judge"], tone: "tone-yellow" },
  { label: "05 / Cloud & Delivery", title: "From commit to cloud", description: "Delivery systems that make shipping repeatable.", skills: ["GCP Cloud Run", "AWS", "Docker", "Kubernetes", "GitHub Actions", "Jenkins", "CI/CD"], tone: "tone-mint" },
  { label: "06 / Identity & Security", title: "Trust by default", description: "Access patterns that work across enterprise products.", skills: ["Keycloak", "OIDC", "OAuth2", "SSO", "Server-side RBAC", "JWT"], tone: "tone-coral" },
];

const experienceHighlights = [
  ["Micro-frontend platform", "Architected and shipped a registry-driven micro-frontend platform with React, TypeScript, and Module Federation. Adopted by 10+ product teams for independent deployments; cut cross-team release coordination from ~3 weeks to 1–2 days. Top contributor over the platform's lifetime."],
  ["Agentic AI service", "Built a production LangGraph multi-agent service in Python that runs CI/CD and DevOps operations through MCP tool servers. Added PostgreSQL-backed task persistence, resume-from-checkpoint flows, and WebSocket + REST interfaces for the platform UI."],
  ["Enterprise identity", "Designed and rolled out Keycloak-based SSO with OIDC/OAuth2 across 10+ applications, synchronized sessions, and server-side RBAC, eliminating a recurring class of cross-app authentication and session-expiry failures."],
  ["Backend-for-frontend", "Built a Node.js/GraphQL BFF aggregating multiple upstream services into one typed schema consumed by every micro-frontend, replacing per-app REST fan-out and cutting page round trips to one."],
  ["Web performance", "Optimized the Next.js 15 shell's Core Web Vitals: LCP 4.2 s → 1.7 s through server rendering, image preloading, route-level code splitting, and shared-dependency de-duplication across federated modules."],
  ["State & quality standards", "Standardized Redux Toolkit state management and Jest/RTL testing across 10+ apps; removed redundant re-renders in shared components and established the platform repo's code-review checklist."],
  ["Technical leadership", "Led a 4-engineer squad delivering real-time CI/CD telemetry dashboards end to end: design reviews, task breakdown, code review, and release, while remaining hands-on across frontend and backend."],
] as const;

export function ClassicPortfolio() {
  const [activeExperience, setActiveExperience] = useState<number | null>(null);
  return (
    <main className="portfolio">
      <CloudShader className="site-background" speed={0.7} count={6} skyTopColor="#3876ba" skyBottomColor="#b7d9ed" />
      <nav className="sitenav" aria-label="Main navigation"><div className="sitenav-inner"><a className="wordmark" href="#top">MANAN SINGH<span>.</span></a><div className="nav-links"><a href="#about">About</a><a href="#skills">Skills</a><a href="#experience">Experience</a><a href="#education">Education</a><a href="#projects">Projects</a><a className="nav-cta" href="#contact">Let&apos;s talk <span>↗</span></a></div></div></nav>
      <section className="hero-split" id="top"><div className="portrait-panel"><div className="portrait-placeholder pixel-portrait"><PixelatedCanvas src="/MANAN%20SINGH.png" width={500} height={620} cellSize={4} dotScale={0.9} interactive distortionStrength={7} distortionRadius={120} tintColor="#ffffff" tintStrength={0.05} /></div><div className="portrait-caption"><span>Manan Singh</span><span>Senior Software Engineer</span></div></div><div className="hero-summary"><p className="eyebrow">Software Engineer <span>Bengaluru, India</span></p><h1>Systems that<br /><em>move ideas forward.</em></h1><p className="summary">I build production-grade platforms, full-stack products, and agentic AI systems for teams solving difficult problems.</p><div className="hero-links"><a href="mailto:singhmanan2001@gmail.com">singhmanan2001@gmail.com <span>↗</span></a><a href="https://github.com/MananSingh2001" target="_blank" rel="noreferrer"><IconBrandGithub size={16} /> GitHub</a><a href="https://linkedin.com/in/manan-singh-sde" target="_blank" rel="noreferrer">LinkedIn <span>↗</span></a></div></div></section>
      <section className="intro-section" id="about"><p className="eyebrow">01 / Professional summary</p><div className="intro-grid"><h2>Full-stack engineer<br /><em>with a systems mind.</em></h2><div><p>Senior Software Engineer I at HCLSoftware with 3 years of experience building production systems used by 10+ product teams.</p><p>I work across frontend architecture, backend services, cloud delivery, identity, and applied AI. My work has cut release coordination from roughly 3 weeks to 1–2 days and improved a Next.js shell&apos;s LCP from 4.2s to 1.7s.</p></div></div></section>
      <section className="skills-reveal" id="skills"><div className="skills-heading"><p className="eyebrow">02 / Toolkit</p><h2>Every system<br /><em>has a shape.</em></h2><p>Explore the tools and disciplines I bring to a build. Click a card to open the full view.</p></div><Carousel items={skillGroups} /></section>
      <section id="experience" className="experience-section experience-lamp-section" style={{ scrollMarginTop: "72px", maxWidth: "none", width: "100vw", marginLeft: "calc(50% - 50vw)", marginRight: "calc(50% - 50vw)" }}><LampContainer className="experience-lamp"><div className="experience-inner"><div className="experience-kicker"><p className="eyebrow">03 / Experience</p><p>Platform and applied-AI engineering<br />for 10+ product teams.</p></div><div className="experience-heading"><div><h2>Experience<br /><em>at HCLSoftware.</em></h2><p className="experience-role"><strong>HCLSoftware (HCL Technologies)</strong><br />Senior Software Engineer I · Bengaluru<br />Oct 2023 — Present</p></div><p>DevOps product suite<br />Enterprise customers</p></div><div className="experience-grid-new">{experienceHighlights.map(([title, description], index) => <WobbleCard containerClassName="experience-card" key={title}><CanvasRevealEffect active={activeExperience === index} className="experience-reveal" /><div className="experience-card-content" onMouseEnter={() => setActiveExperience(index)} onMouseLeave={() => setActiveExperience(null)}><span>0{index + 1}</span><h3>{title}</h3><p>{description}</p></div></WobbleCard>)}</div></div></LampContainer></section>
      <section id="education" className="education-section" style={{ scrollMarginTop: "72px" }}><BackgroundLines><div className="education-inner"><p className="eyebrow">04 / Education &amp; certifications</p><div className="education-grid"><div><h2>Computer Science<br /><em>in practice.</em></h2><p className="degree">B.Tech, Computer Science &amp; Engineering</p><p className="institution">Raj Kumar Goel Institute of Technology (AKTU)</p><p className="education-meta">2023 <span>CGPA 8.58 / 10</span></p></div><div className="certifications"><p className="certification-label">Certifications</p><div className="certification-list"><div><strong>Anthropic MCP Developer</strong><span>Core + Advanced</span></div><div><strong>Google Cloud Gen AI Academy APAC</strong><span>2026</span></div><div><strong>AWS Certified Cloud Practitioner</strong><span>Cloud foundations</span></div></div></div></div></div></BackgroundLines></section>
      <section className="case-section" id="casestudy"><div className="case-inner"><p className="eyebrow">{caseStudy.tag}</p><div className="case-head"><h2>{caseStudy.title}<br /><em>{caseStudy.titleEm}</em></h2><p className="case-problem">{caseStudy.problem}</p></div><div className="case-grid"><div className="case-col"><h4>Architecture</h4><div className="case-flow">{caseStudy.arch.map((s) => <span key={s}>{s}</span>)}</div><h4>Key decisions</h4><ul className="case-list">{caseStudy.decisions.map((d) => <li key={d}>{d}</li>)}</ul></div><div className="case-col"><div className="case-metrics">{caseStudy.results.map((r) => <div className="case-metric" key={r.k}><strong>{r.v}</strong><span>{r.k}</span><small>{r.note}</small></div>)}</div><p className="case-caveat">{caseStudy.caveat}</p><div className="case-links"><a href={caseStudy.repo} target="_blank" rel="noreferrer">Repository ↗</a><a href={caseStudy.live} target="_blank" rel="noreferrer">Live demo ↗</a></div></div></div></div></section>
      <span id="projects" className="section-anchor" aria-hidden="true" /><ProjectShowcase />
      <footer id="contact" className="footer"><p><small>06 / Contact</small><br />Let&apos;s connect<br /><em>and build well.</em></p><a href="mailto:singhmanan2001@gmail.com">singhmanan2001@gmail.com <span>↗</span></a><div className="footer-bottom"><span>© 2026 Manan Singh</span><span><a href="https://linkedin.com/in/manan-singh-sde" target="_blank" rel="noreferrer">LinkedIn</a>&nbsp;&nbsp; <a href="https://github.com/MananSingh2001" target="_blank" rel="noreferrer">GitHub</a></span><span>Open source contributor</span></div></footer>
    </main>
  );
}
